{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tweenr
  version: {{ version|replace("-", "_") }}

source:
  fn: tweenr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tweenr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tweenr/tweenr_{{ version }}.tar.gz
  sha256: d045164692f311f6d73c48b0530db56a101439a646ea6c8c6aed377782a52865

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-farver
    - r-magrittr
    - r-rlang
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.3
    - r-farver
    - r-magrittr
    - r-rlang

test:
  commands:
    - $R -e "library('tweenr')"           # [not win]
    - "\"%R%\" -e \"library('tweenr')\""  # [win]

about:
  home: https://github.com/thomasp85/tweenr
  license: MIT
  summary: In order to create smooth animation between states of data, tweening is necessary.
    This package provides a range of functions for creating tweened data that can be
    used as basis for animation. Furthermore  it adds a number of vectorized interpolaters
    for common R data  types such as numeric, date and colour.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
