# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "A0AwEw6IpzdJIKyFaoqykI4jXeKe96Mf76q+vRTNj6e+6Ur7tTyIysqMf/vJh2iMIUKNjhP812pUId62Xre9PjICN3nVb+NxU0ZJea84xxXcfWscFj89N2IY+lHb3TWlTC4PuTr2ajYcK/J05b9khjH9DPl0htYgyBdPzyEP12CW3YfUzYxPq7y00oCrnV/Wi5enM/F69zg2z+uf3YOv1vijUaB7ZcyXeG/ShTX34ONN0eJWtTSgZEM90Sj3r3WNCsOrn09Q6/7ECSNn0AbhwjA/Hx6/+cOB2nyPIAjooCDW7CsnkSEkmRXvZRHe1EVZst+RXAltJ/6OOLJH8foCnanHppSE14jdfBfUXgPGypqJmbj+GaL8sWkct+lV/WYPMNuDmTAHiU0bxneitFn70NFP4k6/8wOQuz4C7Ah2OAz0HoF/q02PKeMSSJ/rkg0p5rNoFAsYXsba09M3zztxYNAAkjFFOqDp3wSiKRd0cLgPiAhck0Na/4Y5cs41N1RyAvFTLcfnzxmD1uBaaeL7XtKp7Lutgd0Jy7TmhuKavdB0fQ/wNRIPNQEeqa+4pzbArI9TA2Wp/9K7KzKut633c+dFgLhHm92Own01VvKzUBVpLYQ0GpPc9e86X7zzzXEpUBUmpTAGA4W/tiRNRxeaYmyGwFLRuBJ9UIn5dslatJM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
