travis:
  secure:
    BINSTAR_TOKEN: nwO1S9csEuiqI+VCJOtyNuHOSutbbkKZRN1bydH6zixdQsZA7mAP4XZmaDz2f+GijJmrHAivzE2L7BQ4d6EuqRE395MyIFsCTNiUUVi/nxJXlTe3mhDFeU0tj+gUachoihLfPFwHHGvTcqZtpDNVvWcXssybO2IffMoS2UnWYznBUq9NENl0xUqmGTV8zzodm+RbEWKP7uC9h8TWMohjEnwWpQDZ/gJohb7xB4F8QJCPd9kgD0LxmFrBokDsrUaWpi3tra2JmM6eWFhk1xuStCIVWSrmlnAhiTfr6exB/iTvVtpsMxh4uJA008IVsxpd/x8/aNzfkaynggwF+7xVKCOGv4BHGX2WcLLCGtCT51z9EjKxQt96q8Kzp/D3XiTwBLovGiu9sZQQKsT2tEtbLTEErDNpaAwjtqbsXlZ7xzXACg5nHkhXwcOEc2pEy8PYiPTfckn+hfUJz0RDFW9GAFiX7INFGu7bFuYMOGWI6GjriwPUFRHmq4sayiRBKvbiG1c/umsTFespMgsfoJ72Ya0FIT2MEKgmG9GjXZ1FOlv4YxRA4h37RIxAsl94nB99cYSA4Wst3r47XuFDsw9X9ulCep16yzedDIYVOfdIDhvapZYmfD8xbG5QqoPTmWpW2893AE2aiekRYv/5teGsXKQeKpXHQk7OSLYUQelQ2SE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
