travis:
  secure:
    BINSTAR_TOKEN: jYdP+XeZGygDIiCOqRqeJHOcH3ITUHqgZN3ar085jt56aLv/ECntxPy+QzFZ3QcB4CVp4y9dBxxoyrxokseQ4MeKSfcw0Avs5Wb5H7W072S48SjySy6lhS38CKTZipCuojlaCKz1opYWNcSs+rWCZCjwL+OT8vTCAS0yk8fLWik61VPMBXWKecLP2abdlJHBmD4VdY7MbJFuWuoz2326Q7g7M12xbSfmsEw23whwZkGx/WxnsQ7GS2mUwlkpTNvLBZRHgWHOElUbHclu2rEG7Ab4Wqr4+i1tEvZmrYwJ2vb8LinisLl74ZqWb2QhO1AeTMV1NG0VOE84ck6nkosBx3e9EsL0SyHzXVJM9xL7r+fCz/WzTbuvrsDD7OZbShC47Qh9EYhs6BE5IodynQ117sOj/ym3CrkchTiN1fXIwJwMKoRw7tm4kLaAimmA+EIbj70WuUJbZUMgAFx1orRU3d83SQFLY45w+r2CBY2YdIIiX16YSSETCJrUkPczBk40BIQhagzR7mAKRASyAw/iFWAhRShz30ptFka+MVsL6BqzlLw78ZsZ1RqXGQVkLkwZycVULuXZfhegzafh6QFFtmeclRlNn7/Lb3Wd2CmP46w9oWK6RQNb5DF9mJ4SAz7gNzDsxtKyYjF6WA0N48malp6/WHmrw6kb2Yfc8mOG9yg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
