travis:
  secure:
    BINSTAR_TOKEN: A0AwEw6IpzdJIKyFaoqykI4jXeKe96Mf76q+vRTNj6e+6Ur7tTyIysqMf/vJh2iMIUKNjhP812pUId62Xre9PjICN3nVb+NxU0ZJea84xxXcfWscFj89N2IY+lHb3TWlTC4PuTr2ajYcK/J05b9khjH9DPl0htYgyBdPzyEP12CW3YfUzYxPq7y00oCrnV/Wi5enM/F69zg2z+uf3YOv1vijUaB7ZcyXeG/ShTX34ONN0eJWtTSgZEM90Sj3r3WNCsOrn09Q6/7ECSNn0AbhwjA/Hx6/+cOB2nyPIAjooCDW7CsnkSEkmRXvZRHe1EVZst+RXAltJ/6OOLJH8foCnanHppSE14jdfBfUXgPGypqJmbj+GaL8sWkct+lV/WYPMNuDmTAHiU0bxneitFn70NFP4k6/8wOQuz4C7Ah2OAz0HoF/q02PKeMSSJ/rkg0p5rNoFAsYXsba09M3zztxYNAAkjFFOqDp3wSiKRd0cLgPiAhck0Na/4Y5cs41N1RyAvFTLcfnzxmD1uBaaeL7XtKp7Lutgd0Jy7TmhuKavdB0fQ/wNRIPNQEeqa+4pzbArI9TA2Wp/9K7KzKut633c+dFgLhHm92Own01VvKzUBVpLYQ0GpPc9e86X7zzzXEpUBUmpTAGA4W/tiRNRxeaYmyGwFLRuBJ9UIn5dslatJM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
