appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: bXzOMUr+8d3rkIVjKEZwI89n6q3T6DWX3rKlFCPpQK9ShezWeblfPSuUtf5E8mvUkXjKJJYqAmQIiBV1jmA6Gfchh4t0Spc2FAz6HosrvTWw2f+vL6uZpkWfMnIKNUMkMPRmDTygSTI/o104iYvhHU0bKYwU1HuzKy2pqC95fC1cSH+nPqq/8nzcxIF9vaKres80HiP2cCJVrd4Yb/dXfURwX5yyJaylkwHBReubhgeou6TwUlbvdJ8rOzu36PHjZ5p5dzhEzWByn4FXqIgJiQKH3gY/mTxpR0N/cwG5iBK3Hvty2yaId+BCCPzIVBIu5uTc/fARipYX47kf8hv1OIwjIsJbAvtu8ibGOn5yWG1coG96ac98EXSgn3Vqsdsc+j8cXfmzusoZQGG90ZvRcRl5y5rLZl0WApVdJKQiVAsoenyveUifd/cf84EiD5WlgqOT07Dv0thfKHbONQ2xuWqkwSCJPvvdHdl0lCLQnwmoaKjFfHzu6FM1zEW5OSCR55ybif3h9tpQXff/pnhXfmWcBxv4eo7qgI7ryKzevkkZbWmu0KVT4UQHcGs/OcRyeb23O9QL0trX+r/OWtg2hE2UXW/Kkg93b0Wih6VjNpF74fiULLATuPVxHHau+BTGCTlvl5Af0v02yZTp4xRArK01vVc9BzHasqUrCWSTUnE=
conda_forge_output_validation: false
